name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Start Docker Compose services
        run: |
          docker compose up

      - name: Install Pytest
        run: |
          pip install pytest

      - name: Run tests
        run: |
          # Добавьте ваши команды для тестирования здесь
          echo "Running tests..."
          pytest test.py

      - name: Stop and remove Docker Compose services
        run: |
          docker compose down